In [1]:
import numpy as np

np.set_printoptions(suppress=True, formatter={'float': '{:0.3f}'.format})

In [2]:
gamma_n = 0.01
beta_n = 1 / (2 * gamma_n)

# Matrice A_{n-1}
vp_min = 1
vp_max = 10
A_0 = np.diag([vp_min, vp_max])
print(f'A:\n {A_0}\n')

# Matrice hessienne de g(X_n, theta_{n-1}) = 
hess = np.array([[101, 10], [10, 1]]) / 11
print(f'h:\n {hess}\n')

# check if hess is definite positive
eig = np.linalg.eigvals(hess)
print(f'valeurs propres:\n {eig}\n')

Z = np.array([0, 1]).reshape(2, 1)
T = hess @ Z @ Z.T
print(f'T:\n {T}\n')
print(f'norm(T):\n {np.linalg.norm(T, ord=2)}')


A:
 [[ 1  0]
 [ 0 10]]

h:
 [[9.182 0.909]
 [0.909 0.091]]

valeurs propres:
 [9.272 0.001]

T:
 [[0.000 0.909]
 [0.000 0.091]]

norm(T):
 0.9136250564655354


In [3]:
print(f'T @ A:\n {T @ A_0}\n')

A_new = A_0 - 0.5 * (A_0 @ T.T + T @ A_0)
print(f'A_new:\n {A_new}\n')



T @ A:
 [[0.000 9.091]
 [0.000 0.909]]

A_new:
 [[1.000 -4.545]
 [-4.545 9.091]]



In [4]:
u = np.array([2,1]).reshape(2,1)

res_sym = u.T @ A_new @ u 
print(f'res_sym: {res_sym}')



res_sym: [[-5.091]]
