In [1]:
import numpy as np

np.set_printoptions(suppress=True, formatter={'float': '{:0.3f}'.format})

In [2]:
gamma_n = 0.1
beta_n = 1 / (2 * gamma_n)
print(f'beta_n: {beta_n}\n')

# Matrice A_{n-1}
vp_min = 1
vp_max = 10
A_0 = np.diag([vp_min, vp_max])
print(f'A:\n {A_0}\n')

# Matrice hessienne de g(X_n, theta_{n-1}) = 
hess = np.array([[101, 10], [10, 1]], dtype=float)
print(f'h:\n {hess}\n')

# check if hess is definite positive
eig = np.linalg.eigvals(hess)
print(f'valeurs propres:\n {eig}\n')

Z = np.array([0, 1]).reshape(2, 1)
Q = hess @ Z
Q *= beta_n / np.linalg.norm(Q, ord=2)
T = np.outer(Q, Z)
print(f'T:\n {T}\n')
print(f'norm(T):\n {np.linalg.norm(T, ord=2)}')


beta_n: 5.0

A:
 [[ 1  0]
 [ 0 10]]

h:
 [[101.000 10.000]
 [10.000 1.000]]

valeurs propres:
 [101.990 0.010]

T:
 [[0.000 4.975]
 [0.000 0.498]]

norm(T):
 5.0


In [3]:
print(f'T @ A:\n {T @ A_0}\n')

A_new = A_0 - gamma_n * (A_0 @ T.T + T @ A_0 - np.eye(2))
print(f'A_new:\n {A_new}\n')



T @ A:
 [[0.000 49.752]
 [0.000 4.975]]

A_new:
 [[1.100 -4.975]
 [-4.975 9.105]]



In [4]:
eig = np.linalg.eigvals(A_new)
print(f'valeurs propres:\n {eig}\n')

valeurs propres:
 [-1.283 11.488]

