In [1]:
import numpy as np


In [2]:
a = 1
b = 2
c = 4
M = np.array([[a, b], [b, c]])

print(M)
print(np.linalg.det(M))
print(np.linalg.eig(M))

[[1 2]
 [2 4]]
0.0
EigResult(eigenvalues=array([0., 5.]), eigenvectors=array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]]))


In [3]:
P = np.array([[1, 0], [0, 0]])

N = P @ M

print(f"N : \n{N}")

eigenval = np.linalg.eig(N)[0]
print(f"eigenval : {eigenval}")

eigenvec = np.linalg.eig(N)[1]
print(eigenvec)


N : 
[[1 2]
 [0 0]]
eigenval : [1. 0.]
[[ 1.         -0.89442719]
 [ 0.          0.4472136 ]]


In [4]:
X = np.array([1, -1])
print(X.T @ N @ X)

-1
